title = "Custom SVG Parametric Clicker Interface"

[[model]]
name = "Fidget Clicker Creator"
file = "clicker.scad"

[[model.parameter]]
id = "part_to_render"
type = "select"
name = "Part to Render"
options = ["housing", "button"] 

[[model.parameter]]
id = "logo_file"
type = "file"
name = "Upload Custom SVG Shape"
accept = ".svg"

[[model.parameter]]
id = "add_keychain"
type = "checkbox"
name = "Add Keychain Loop"

[[model.parameter]]
id = "keychain_offset"
type = "number"
name = "Keychain Loop Distance"
min = 15
max = 60
step = 1

[[model.parameter]]
id = "button_text"
type = "text"
name = "Button Text Engraving"

[[model.parameter]]
id = "text_size"
type = "number"
name = "Text Font Size"
min = 3
max = 15
step = 0.5
